init commit
adrzdv/java-explore-with-me pull request #1
Opened 2024-12-05 13:46 UTC by adrzdv

2024-12-06 13:53 UTC, kriwsha requested changes

2024-12-06 13:53 UTC, kriwsha commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +    public <T> ResponseEntity<Object> hitUri(String app, String uri, String ip, LocalDateTime timestamp) {
У вас метод не является дженериком - все типы определены, а возвращаете вы Object, поэтому не нужно указывать <T>

2024-12-06 13:53 UTC, kriwsha commented on stats/stats-client/src/main/java/ru/practicum/ewm/StatsClient.java
> +    public <T> ResponseEntity<Object> getStats(LocalDateTime start, LocalDateTime end,
Здесь и ниже также следует убрать <T> либо переделать метод под дженерик

2024-12-06 13:53 UTC, kriwsha commented on stats/stats-dto/src/main/java/ru/practicum/statsdto/HitObject.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Очень скептически отношусь к этой аннотации - ни разу на реальных проектах ее не встречал. Кроме того, получается, что у вас в части кода есть модификаторы доступа - в другой части вы используете аннотацию. Но это только рекомендация

2024-12-06 13:53 UTC, kriwsha commented on stats/stats-dto/src/main/java/ru/practicum/statsdto/HitObjectProjection.java
> +    String getApp();
Не забывайте документировать методы. В интерфейсах это наиболее критично

2024-12-06 14:20 UTC, adrzdv commented on stats/stats-dto/src/main/java/ru/practicum/statsdto/HitObjectProjection.java
> +    String getApp();
Согласен, однако это же проекция объекта HitObject и она у нас для внутреннего пользования и тут нет никакого неочевидного поведения

2024-12-07 13:38 UTC, kriwsha approved these changes

2024-12-07 14:17 UTC, merged